services:
  ######################### NPM #####################################
  # Should not run the whole time, only when a npm command is run
  npm:
    container_name: i_iv_v_npm
    image: node:23
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    # command: ["/bin/sh", "-c", "npm install && npm run build"]

  ######################### Frontend Service #######################
  frontend:
    container_name: ri_iv_v_dev
    image: node:23
    volumes:
      - ./app:/var/www/html
    ports:
      - "5173:5173"
    working_dir: /var/www/html
    command: ["/bin/sh", "-c", "npm install && npm run dev -- --host"]

  